# Python CircleCI 2.0 configuration file
# 
# Check https://circleci.com/docs/2.0/language-python/ for more details
# 
version: 2.1
jobs:
  lint_step:
    docker:
      - image: python:3.7.3-stretch
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate                                                                
            make install
      # run lint!
      - run:
          name : run lint
          command: |
                  . venv/bin/activate
                  make lint
  docker_build:
    docker:
      - image: circleci/golang:1.15
        auth:
             username: $DOCKER_USERNAME
             password: $DOCKER_PASSWORD
    steps:
            - checkout
            - setup_remote_docker
            - run:
                  name: Push image to a docker repository
                  command: |
                          docker build --tag=capstone.ang .
                          docker image ls
                          dockerpath=angeline95/capstone.ang
                          echo "Docker ID and Image: $dockerpath"
                          docker login -u angeline95 -p $DOCKER_PASSWORD &&\
                                    docker tag capstone.ang $dockerpath
                          docker push $dockerpath
                  
  Deploy_to_Kube:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            apt-get -y -qq update
            apt-get -y install sudo

            # install AWS CLI
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
            
            # Install kubectl
            curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.19.6/2021-01-05/bin/linux/amd64/kubectl
            chmod +x ./kubectl
            mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$PATH:$HOME/bin
            
            # Install eksctl
            curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
            sudo mv /tmp/eksctl /usr/local/bin
      - run:
          name: Build cluster
          command: |
            chmod 755 create_kube.sh
            ./create_kube.sh
                  
workflows:
  default:
    jobs:
      - lint_step
      - docker_build:
          requires: [lint_step]
      - Deploy_to_Kube
          requires: [Build_DockerApp]
