# Python CircleCI 2.0 configuration file
# 
# Check https://circleci.com/docs/2.0/language-python/ for more details
# 
version: 2
jobs:
  lint_step:
    docker:
      - image: python:3.7.3-stretch
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate                                                                
            make install
      # run lint!
      - run:
          name : run lint
          command: |
                  . venv/bin/activate
                  make lint
  docker_build:
    docker:
      - image: circleci/golang:1.15
        auth:
             username: $DOCKER_USERNAME
             password: $DOCKER_PASSWORD
    steps:
            - checkout
            - setup_remote_docker
            - run:
                  name: Push image to a docker repository
                  command: |
                          docker build --tag=capstone_proj .
                          docker image ls
                          dockerpath=angeline95/capstone_proj
                          echo "Docker ID and Image: $dockerpath"
                          echo $DOCKER_PASS | docker login -u angeline95 --password-stdin &&\
                                    docker image tag capstone_proj $dockerpath
                          docker image push $dockerpath
workflows:
  default:
    jobs:
      - lint_step
      - docker_build:
          requires: [lint_step]
